var res = {
	HelloWorld_png : "res/HelloWorld.png",
    entry_csd : "res/entry.json",
    entry_animation_csd : "res/entry_animation.json",
    create_room_csd : "res/create_room_animation.json",
    join_room_csd : "res/join_room_animation.json",
    game_room_csd : "res/game_room.json",
    game_room2_csd : "res/game_room2.json",
    game_room3_csd : "res/game_room3.json",
    common_dialog_csd : "res/common_dialog_animation.json",
    share_dialog_csd : "res/share_dialog_animation.json",
    message_dialog_csd : "res/message_dialog_animation.json",
    manual_dialog_csd : "res/manual_dialog_animation.json",
    setting_dialog_csd : "res/setting_dialog_animation.json",
    history_dialog_csd : "res/history_record_dialog_animation.json",
    emotion_dialog_csd : "res/emotion_dialog.json",
    shopping_dialog_csd : "res/shopping_dialog_animation.json",
    score_point_csd : "res/score_point.json",
    player_round_result_csd : "res/player_round_result.json",
    round_result_csd : "res/round_result.json",
    round_detail_csd : "res/round_detail_animation.json",
    login_scene_csd : "res/login_scene.json",
    room_record_csd : "res/room_record_dialog_animation.json",
    gov_ntf_dialog_csd : "res/gov_ntf_dialog.json",
    dismiss_room_csd : "res/dissolution_room_animation.json",
    logo_csd : "res/logo.json",
    game_result_csd : "res/game_result.json",
    create_chat_room_csd: "res/create_chatroom_animation.json",
    register_dialog_csd: "res/register.json",
    ip_dialog_csd: "res/ip.json",
    message_content_csd: "res/message_content.json",
    dapai_animation_csd: "res/dapai_animation.json",
    login_agreement_animation_csd: "res/login_agreement_animation.json",
    server_list_csd: "res/server_list.json",
    server_config_csd: "res/server_config.json",
    update_dialog_csd: "res/update_dialog.json",
    game_result_texiao_csd: "res/game_result_texiao.json",
    player_info_dialog_csd: "res/player_info_dialog.json",
    arrow_csd: "res/arrow.json",
    mahjong_choose_csd: "res/mahjong_choose.json",
    sprint_chicken_csd: "res/sprint_chicken.json",
    duty_chicken_csd: "res/duty_chicken.json",
    catch_chicken_csd: "res/catch_chicken.json",
    dianpao_csd: "res/dianpao.json",
    zimo_csd: "res/zimo.json",
    chi_csd: "res/chi.json",
    gang_csd: "res/gang.json",
    peng_csd: "res/peng.json",
    ting_csd: "res/ting.json",
    huangzhuang_csd: "res/huangzhuang.json",
    game_room_pad_csd: "res/game_room_pad.json",
    game_room2_pad_csd: "res/game_room2_pad.json",
    game_room3_pad_csd: "res/game_room3_pad.json",
    logger_csd : "res/logger_dialog.json",
    join_room_anim_csd : "res/loading_join_room.json",
    login_anim_csd : "res/loading_Log_in_to.json",
    common_mask_csd: "res/common_mask.json",
    top_message_csd: "res/top_message.json",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
